# cloudbuild.yaml

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: './ConnectBot'
    args: 
      [
        'build',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}',
        '.'
      ]
    env:
      - 'REGION=${_REGION}'
      - 'REPO_NAME=${_REPO_NAME}'
      - 'IMAGE_NAME=${_IMAGE_NAME}'

  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      ]
    env:
      - 'REGION=${_REGION}'
      - 'REPO_NAME=${_REPO_NAME}'
      - 'IMAGE_NAME=${_IMAGE_NAME}'

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_IMAGE_NAME}'
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
    env:
      - 'REGION=${_REGION}'

substitutions:
  _REGION: 'europe-north1'                   # Replace with your desired GCP region
  _REPO_NAME: 'connectbot'            # Replace with your Artifact Registry repository name
  _IMAGE_NAME: 'connectbot'          # Replace with the desired image name

options:
  logging: CLOUD_LOGGING_ONLY
